# Generated by Django 3.1.1 on 2020-09-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_url', models.CharField(default='', max_length=300, verbose_name='基金链接')),
                ('fund_code', models.CharField(db_index=True, default='', max_length=20, unique=True, verbose_name='基金代码')),
                ('fund_name', models.CharField(default='', max_length=200, verbose_name='基金名称')),
                ('fund_manager', models.CharField(default='', max_length=200, verbose_name='基金经理')),
                ('fund_company', models.CharField(default='', max_length=200, verbose_name='基金公司')),
                ('fund_type', models.CharField(default='', max_length=200, verbose_name='基金类型')),
                ('fund_short_name', models.CharField(default='', max_length=200, verbose_name='基金简称')),
                ('pinyin_abbreviation_code', models.CharField(default='', max_length=200, verbose_name='基金首字母缩写')),
                ('establish_date', models.DateField(default='', verbose_name='基金创立日期')),
                ('handling_fee', models.FloatField(default=0, verbose_name='手续费率')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('can_buy', models.BooleanField(default=False, verbose_name='可否购买')),
            ],
        ),
        migrations.CreateModel(
            name='FundLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='爬取名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('total_fund', models.PositiveIntegerField(default=0, verbose_name='基金总数')),
                ('stock_fund_num', models.PositiveIntegerField(default=0, verbose_name='股票型基金总数')),
                ('hybrid_fund_num', models.PositiveIntegerField(default=0, verbose_name='混合型基金总数')),
                ('bond_fund_num', models.PositiveIntegerField(default=0, verbose_name='债券型基金总数')),
                ('index_fund_num', models.PositiveIntegerField(default=0, verbose_name='指数基金总数')),
                ('break_even_fund_num', models.PositiveIntegerField(default=0, verbose_name='保本型基金总数')),
                ('qdii_fund_num', models.PositiveIntegerField(default=0, verbose_name='QDII 型基金总数')),
                ('etf_fund_num', models.PositiveIntegerField(default=0, verbose_name='ETF 型基金总数')),
                ('lof_fund_num', models.PositiveIntegerField(default=0, verbose_name='LOF型基金总数')),
                ('fof_fund_num', models.PositiveIntegerField(default=0, verbose_name='FOF型基金总数')),
            ],
        ),
        migrations.CreateModel(
            name='FundHistoricalNetWorthRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(db_index=True, default='', max_length=20, verbose_name='基金代码')),
                ('update_date', models.DateField(verbose_name='当前日期')),
                ('start_unit_net_worth', models.FloatField(default=0, verbose_name='起始单位净值')),
                ('start_cumulative_net_worth', models.FloatField(default=0, verbose_name='起始累计净值')),
                ('current_unit_net_worth', models.FloatField(default=0, verbose_name='当前单位净值')),
                ('current_cumulative_net_worth', models.FloatField(default=0, verbose_name='当前累计净值')),
                ('daily', models.FloatField(default=0, verbose_name='日涨跌幅')),
                ('last_week', models.FloatField(default=0, verbose_name='周涨跌')),
                ('last_month', models.FloatField(default=0, verbose_name='最近一个月涨跌')),
                ('last_three_month', models.FloatField(default=0, verbose_name='最近三个月涨跌')),
                ('last_six_month', models.FloatField(default=0, verbose_name='最近六个月涨跌')),
                ('last_year', models.FloatField(default=0, verbose_name='最近一年涨跌')),
                ('last_two_year', models.FloatField(default=0, verbose_name='最近两年涨跌')),
                ('last_three_year', models.FloatField(default=0, verbose_name='最近三年涨跌')),
                ('this_year', models.FloatField(default=0, verbose_name='今年以来涨跌')),
                ('since_founded', models.FloatField(default=0, verbose_name='成立以来涨跌')),
                ('handling_fee', models.FloatField(default=0, verbose_name='手续费率')),
                ('subscription_status', models.CharField(default='', max_length=20, verbose_name='申购状态')),
                ('redemption_status', models.CharField(default='', max_length=20, verbose_name='赎回状态')),
                ('dividend_distribution', models.CharField(default='', max_length=200, verbose_name='分红送配')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
            options={
                'unique_together': {('fund_code', 'update_date')},
            },
        ),
    ]
