# Generated by Django 3.1.1 on 2020-09-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_url', models.CharField(default='', max_length=300, verbose_name='基金链接')),
                ('fund_code', models.CharField(default='', max_length=20, verbose_name='基金代码')),
                ('fund_name', models.CharField(default='', max_length=200, verbose_name='基金名称')),
                ('fund_short_name', models.CharField(default='', max_length=200, verbose_name='基金简称')),
                ('update_date', models.DateTimeField(verbose_name='当前日期')),
                ('unit_net_worth', models.FloatField(default=0, verbose_name='单位净值')),
                ('cumulative_net_worth', models.FloatField(default=0, verbose_name='累计净值')),
                ('daily', models.FloatField(default=0, verbose_name='日涨跌幅')),
                ('last_week', models.FloatField(default=0, verbose_name='周涨跌')),
                ('last_month', models.FloatField(default=0, verbose_name='最近一个月涨跌')),
                ('last_three_week', models.FloatField(default=0, verbose_name='最近三个月涨跌')),
                ('last_six_month', models.FloatField(default=0, verbose_name='最近六个月涨跌')),
                ('last_year', models.FloatField(default=0, verbose_name='最近一年涨跌')),
                ('last_two_year', models.FloatField(default=0, verbose_name='最近两年涨跌')),
                ('last_three_year', models.FloatField(default=0, verbose_name='最近三年涨跌')),
                ('this_year', models.FloatField(default=0, verbose_name='今年以来涨跌')),
                ('since_founded', models.FloatField(default=0, verbose_name='成立以来涨跌')),
                ('handling_fee', models.FloatField(default=0, verbose_name='手续费率')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
        ),
    ]
