# Generated by Django 3.1.1 on 2020-09-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='last_three_week',
            new_name='last_three_month',
        ),
    ]
