# Generated by Django 3.1.1 on 2020-09-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundhistoricalnetworthranking',
            name='dividend_distribution',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='分红送配'),
        ),
        migrations.AlterField(
            model_name='fundhistoricalnetworthranking',
            name='redemption_status',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='赎回状态'),
        ),
        migrations.AlterField(
            model_name='fundhistoricalnetworthranking',
            name='subscription_status',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='申购状态'),
        ),
    ]
