# Generated by Django 3.1.1 on 2020-09-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0002_auto_20200920_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_url',
        ),
    ]
