# Generated by Django 3.1.1 on 2020-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0002_auto_20200920_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='基金经理')),
                ('manager_id', models.IntegerField(unique=True, verbose_name='基金经理id')),
            ],
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='annualized_income_14day',
            field=models.FloatField(default=0, verbose_name='14天年化收益率'),
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='annualized_income_28day',
            field=models.FloatField(default=0, verbose_name='28天年化收益率'),
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='annualized_income_7day',
            field=models.FloatField(default=0, verbose_name='7天年化收益率'),
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='ten_thousand_income',
            field=models.FloatField(default=0, verbose_name='万份收益'),
        ),
    ]
