# Generated by Django 3.1.1 on 2020-09-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0002_auto_20200918_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('total_fund', models.PositiveIntegerField(default=0, verbose_name='基金总数')),
            ],
        ),
    ]
