# Generated by Django 3.1.1 on 2020-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_auto_20201002_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundManagerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(default='', max_length=20, verbose_name='基金代码')),
                ('manager_id', models.CharField(max_length=20, unique=True, verbose_name='基金经理 id')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
            options={
                'unique_together': {('fund_code', 'manager_id')},
            },
        ),
    ]
