# Generated by Django 3.1.1 on 2020-09-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_fundlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fund',
            unique_together={('fund_url', 'fund_code', 'fund_name', 'update_date')},
        ),
    ]
