# Generated by Django 3.1.1 on 2020-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_auto_20201001_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='last_five_year',
            field=models.FloatField(default=0, verbose_name='最近五年涨跌'),
        ),
    ]
