# Generated by Django 3.1.1 on 2020-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_remove_fund_fund_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundhistoricalnetworthranking',
            name='current_date',
            field=models.DateField(default='', verbose_name='当前日期'),
        ),
    ]
