# Generated by Django 3.1.1 on 2020-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0004_auto_20200920_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='since_founded_bonus',
            field=models.FloatField(default=0, verbose_name='成立以来分红'),
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='since_founded_bonus_num',
            field=models.IntegerField(default=0, verbose_name='成立以来分红次数'),
        ),
        migrations.AddField(
            model_name='fundhistoricalnetworthranking',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
    ]
