# Generated by Django 3.1.1 on 2020-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0004_auto_20200918_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='update_date',
            field=models.DateField(verbose_name='当前日期'),
        ),
    ]
