# Generated by Django 3.1.1 on 2020-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0004_fundhistoricalnetworthranking_last_five_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='establish_date',
            field=models.DateField(default='', null=True, verbose_name='基金创立日期'),
        ),
    ]
