# Generated by Django 3.1.1 on 2020-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0005_auto_20200919_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_code',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='基金代码'),
        ),
    ]
