# Generated by Django 3.1.1 on 2020-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcompany',
            name='update_date',
            field=models.DateField(null=True, verbose_name='数据更新时间'),
        ),
    ]
