# Generated by Django 3.1.1 on 2020-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0004_fundmanagerrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmanagerrelationship',
            name='manager_id',
            field=models.CharField(max_length=20, verbose_name='基金经理 id'),
        ),
    ]
