# Generated by Django 3.1.1 on 2020-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0005_auto_20201002_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='initial_purchase_amount',
            field=models.FloatField(default=0, verbose_name='起购金额'),
        ),
    ]
