# Generated by Django 3.1.1 on 2020-10-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0006_fund_initial_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_company_id',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_id',
        ),
    ]
