# Generated by Django 3.1.1 on 2020-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0007_auto_20201002_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='任务名')),
                ('status', models.CharField(default='', max_length=100, verbose_name='任务状态')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否删除')),
            ],
        ),
        migrations.AlterField(
            model_name='fundcompany',
            name='tianxiang_star',
            field=models.PositiveIntegerField(default=0, verbose_name='天相评级(0星到五星)'),
        ),
        migrations.AlterField(
            model_name='fundmanager',
            name='total_asset_manage_amount',
            field=models.FloatField(default=0, verbose_name='基金资产管理总规模(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundmanager',
            name='working_time',
            field=models.IntegerField(default=0, verbose_name='从业时间(天)'),
        ),
    ]
