# Generated by Django 3.1.1 on 2020-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0008_auto_20201014_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtask',
            name='func',
            field=models.CharField(default='', max_length=200, verbose_name='执行函数名'),
        ),
    ]
