# Generated by Django 3.1.1 on 2020-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0009_fundtask_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtask',
            name='func',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='执行函数名'),
        ),
    ]
